#version 460 core

#include "../common.glsl"

layout(local_size_x = 16, local_size_y = 16) in;

layout(rgba32f, binding = 0) writeonly uniform image2D imgOutput;

uniform float u_worldSize;
uniform float u_wavelength;
uniform float u_speed;
uniform float u_amplitude;
uniform float u_persistence;
uniform float u_lacunarity;
uniform float u_speedMul;
uniform float u_dragMul;
uniform float u_time;
uniform int u_count;

void main() {
  ivec2 texCoord = ivec2(gl_GlobalInvocationID.xy);
  ivec2 size = imageSize(imgOutput);
  if (texCoord.x >= size.x || texCoord.y >= size.y)
    return;

  float twoOverWavelength = 2.f / u_wavelength;
  float totalWave = 0.f;
  vec2 totalSlope = vec2(0.f);
  vec2 uv = vec2(texCoord) / vec2(size - 1);
  vec2 worldPos = uv * u_worldSize;

  float alpha = u_amplitude;
  float omega = twoOverWavelength;           // Frequency
  float phase = u_speed * twoOverWavelength; // Move

  for (int i = 0; i < u_count; i++) {
    float angleStep = float(i) * GOLDEN_ANGLE;
    vec2 dir = vec2(sin(angleStep), cos(angleStep));

    float angle = dot(dir, worldPos) * omega + u_time * phase;
    float sharpWave = exp(sin(angle) - 1.f);
    float wave = alpha * sharpWave;

    totalWave += wave;

    float derivativeFactor = wave * omega * cos(angle);
    vec2 slope = dir * derivativeFactor;

    worldPos += slope * u_dragMul;
    totalSlope += slope;

    alpha *= u_persistence;
    omega *= u_lacunarity;
    phase *= u_speedMul;
  }

  vec3 normal = normalize(vec3(-totalSlope.x, 1.f, -totalSlope.y));

  // Store: RGB = Normal, A = Height
  imageStore(imgOutput, texCoord, vec4(normal, totalWave));
}

