#version 460 core

#include "../../common.glsl"

layout (local_size_x = 16, local_size_y = 16) in;

layout (rg32f, binding = 0) uniform readonly  image2D imgWaveHeightFieldTimeEvolution_IFFT;
layout (rg32f, binding = 1) uniform readonly  image2D imgWaveChoppyX_IFFT;
layout (rg32f, binding = 2) uniform readonly  image2D imgWaveChoppyZ_IFFT;
layout (rgba32f, binding = 3) uniform writeonly image2D imgDisplacement;

uniform float u_choppinessControl;

void main() {
  ivec2 texCoord = ivec2(gl_GlobalInvocationID.xy);
  ivec2 size = imageSize(imgWaveHeightFieldTimeEvolution_IFFT);

  float rawX = imageLoad(imgWaveChoppyX_IFFT, texCoord).r;
  float rawY = imageLoad(imgWaveHeightFieldTimeEvolution_IFFT, texCoord).r;
  float rawZ = imageLoad(imgWaveChoppyZ_IFFT, texCoord).r;

  float sizeSq = size.x * size.y;
  float sizeSqInv = 1.f / sizeSq;
  float permutationSign = ((texCoord.x + texCoord.y) & 1) == 0 ? 1.f : -1.f;

  float displacementX = rawX * sizeSqInv * permutationSign * u_choppinessControl;
  float displacementY = rawY * sizeSqInv * permutationSign;
  float displacementZ = rawZ * sizeSqInv * permutationSign * u_choppinessControl;

  imageStore(imgDisplacement, texCoord, vec4(displacementX, displacementY, displacementZ, 1.f));
}

