#version 460 core

#include "../../common.glsl"

layout(local_size_x = 16, local_size_y = 16) in;

layout(rgba32f, binding = 0) readonly uniform image2D imgWaveHeightField;
layout(rg32f, binding = 1) writeonly uniform image2D imgWriteHeight;
layout(rg32f, binding = 2) writeonly uniform image2D imgWriteChoppyX;
layout(rg32f, binding = 3) writeonly uniform image2D imgWriteChoppyZ;

uniform float u_worldSize;
uniform float u_time;

void main() {
  ivec2 texCoord = ivec2(gl_GlobalInvocationID.xy);
  ivec2 size = imageSize(imgWriteHeight);

  vec4 data = imageLoad(imgWaveHeightField, texCoord);

  float theta = data.a * u_time;
  vec2 expPos = vec2(cos(theta),  sin(theta));
  vec2 expNeg = vec2(cos(theta), -sin(theta));

  ivec2 negTexCoord = (size - texCoord) % size;
  vec2 h0_k = data.rg;
  vec2 h0_minus_k = imageLoad(imgWaveHeightField, negTexCoord).rg;

  // Complex Conjugate of h0(-k) -> negate the Imaginay (Y) component
  vec2 h0_minus_k_conj = vec2(h0_minus_k.x, -h0_minus_k.y);

  vec2 term1 = complexMultiply(h0_k, expPos);
  vec2 term2 = complexMultiply(h0_minus_k_conj, expNeg);
  vec2 h_k_t = term1 + term2;

  float n = texCoord.x - size.x / 2;
  float m = texCoord.y - size.y / 2;

  float kx = (TAU * n) / u_worldSize;
  float kz = (TAU * m) / u_worldSize;

  vec2 k_wavevector = vec2(kx, kz);
  float k_magnitudeSq = dot(k_wavevector, k_wavevector);
  vec2 choppySpectrumX = vec2(0.f);
  vec2 choppySpectrumZ = vec2(0.f);

  if (k_magnitudeSq > 1e-4f) {
    float k_magnitude = sqrt(k_magnitudeSq);
    vec2 k_dir = k_wavevector / k_magnitude;

    vec2 ih = vec2(-h_k_t.y, h_k_t.x);
    choppySpectrumX = ih * k_dir.x;
    choppySpectrumZ = ih * k_dir.y;
  }

  imageStore(imgWriteHeight, texCoord, vec4(h_k_t, 0.f, 1.f));
  imageStore(imgWriteChoppyX, texCoord, vec4(choppySpectrumX, 0.f, 1.f));
  imageStore(imgWriteChoppyZ, texCoord, vec4(choppySpectrumZ, 0.f, 1.f));
}

