#version 460 core

#include "../../common.glsl"

layout(local_size_x = 8, local_size_y = 8) in;

layout(rgba32f, binding = 0) readonly  uniform image2D imgPrecomputedData;
layout(rg32f  , binding = 1) readonly  uniform image2D imgRead;
layout(rg32f  , binding = 2) writeonly uniform image2D imgWrite;

uniform int u_step;

void main() {
  ivec2 id = ivec2(gl_GlobalInvocationID.xy);

  vec4 data = imageLoad(imgPrecomputedData, ivec2(u_step, id.x));
  ivec2 inputIndices = ivec2(data.ba);

  vec2 complexAmplitude0 = imageLoad(imgRead, ivec2(inputIndices.x, id.y)).rg;
  vec2 complexAmplitude1 = imageLoad(imgRead, ivec2(inputIndices.y, id.y)).rg;
  vec2 sumResult = complexAmplitude0 + complexMultiply(vec2(data.r, -data.g), complexAmplitude1);

  imageStore(imgWrite, id, vec4(sumResult, 0.f, 1.f));
}

