#version 460 core

#include "../../common.glsl"

layout (local_size_x = 16, local_size_y = 16) in;

layout (rg32f, binding = 0) uniform readonly  image2D imgInput;
layout (rg32f, binding = 1) uniform writeonly image2D imgOutput;

uniform int u_stage;

void main() {
  ivec2 texCoord = ivec2(gl_GlobalInvocationID.xy);
  int size = imageSize(imgInput).x;

  int n = texCoord.x < size / 2 ? texCoord.x : texCoord.x - size;
  int isEvenBlock = n / u_stage;
  int localIdx = n % u_stage;

  int j0 = isEvenBlock * u_stage * 2 + localIdx;
  int j1 = j0 + u_stage;

  vec2 p = imageLoad(imgInput, ivec2(j0, texCoord.y)).rg;
  vec2 q = imageLoad(imgInput, ivec2(j1, texCoord.y)).rg;

  float angle = (TAU * float(localIdx)) / float(u_stage * 2);
  vec2 twiddle = vec2(cos(angle), sin(angle));

  float sumSign = texCoord.x < size ? 1.f : -1.f;
  vec2 result = p + complexMultiply(twiddle, q) * sumSign;

  imageStore(imgOutput, texCoord, vec4(result, 0.0f, 1.0f));
}

